### ISSUE TITLE
Attempting to Sync Steam to Microsoft results in brand new Microsoft Save after booting the game in Xbox

### ISSUE THREAD

**Issue by eric-endsley** [ntaiprogrammer/Mollys_GameSave_Mule#1]
I just recently installed DRG on the XBOX store to play with console friends. My first attempt I just booted up the XBOX version, hit skip tutorial, then exit to desktop. Then tried to sync the saves. Next time I logged into DRG, it restarted me in the tutorial, and a *new* XBOX save was generated by the game (with a new title), deleting the old one. 

I tried playing through the tutorial and an online mission, to see if this made any difference, but it did not.

I've also tried the same steps with manually overwriting the save, and that was the same result as well, which makes me wonder if this hack no longer works in general.

Any insight you may have would be greatly appreciated. Thanks!

**Comment by ntaiprogrammer** [comment]
> 

This happens sometimes, I suspect because the Steam version receives patches/updates before Xbox does and this may result in the Steam version being different enough that Xbox won't accept the save file until both platforms are on the exact same version. Eventually it will just start working again.

For now, you can restore whatever progress your Xbox version had before the wipe by using the Restore Save function in the Saves menu within the game.

**Comment by eric-endsley** [comment]
Thanks friend, you were totally correct. The sync worked when I attempted it tonight. Thanks for making this, and your response! 👍

**Comment by ntaiprogrammer** [comment]
> Thanks friend, you were totally correct. The sync worked when I attempted it tonight. Thanks for making this, and your response! 👍

You're welcome, glad you're liking the app :)
